[package]
name = "buffrs-registry"
version = "0.1.0"
edition = "2021"
description = "Registry for buffrs, a modern protocol buffer package manager"
license = "Apache-2.0"

[dependencies]
buffrs = { path = "../", version = "0.7.0" }
prost = "0.12.1"
tonic = "0.10.2"
clap = { version = "4.3", features = ["cargo", "derive", "env"] }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
sqlx = { version = "0.7.2", features = ["runtime-tokio", "postgres", "macros", "migrate"] }
eyre = "0.6.8"
url = "2.4.1"
axum_tonic = "0.1.0"
async-trait = "0.1.74"
semver = "1.0.20"
thiserror = "1.0.49"
ssh-key = { version = "0.6.2", features = ["ed25519"] }
bytes = "1.5.0"
miette = "5.10.0"
moka = { version = "0.12.1", optional = true, features = ["future"] }

[build-dependencies]
buffrs = { path = "../", version = "0.7.0" }

[features]
default = ["storage-cache"]
test-database = []
storage-cache = ["dep:moka"]

[dev-dependencies]
proptest = "1.3.1"
tempdir = "0.3.7"
